# 1. Backend Deploy
- name: Deploy Backend Application
  hosts: backend
  become: yes
  tasks:
    - name: Stop old backend container (if running)
      shell: docker stop backend || true

    - name: Remove old backend container
      shell: docker rm backend || true

    - name: Pull Docker Image
      shell: docker pull chamod12/car-backend:latest

    # --- Debugging: Environment Variables Check ---
    - name: Run Backend Container
      shell: >
        docker run -d --name backend -p 5000:5000
        -e MONGODB_URI="mongodb+srv://admin:Chamod12@cluster0.miiguq0.mongodb.net/car_rental?retryWrites=true&w=majority&appName=Cluster0"
        -e PORT=5000
        -e JWT_SECRET=supersecretkey123
        -e CLOUDINARY_CLOUD_NAME="dkcgak6lq"
        -e CLOUDINARY_API_KEY="952538291321884"
        -e CLOUDINARY_API_SECRET="nMTrjCRo1Wr-c0e1eMbSbRJof40"
        chamod12/car-backend:latest

    # --- Debugging: Wait and Check Logs ---
    - name: Wait for Backend to start (15 seconds)
      pause:
        seconds: 15

    - name: Get Backend Logs (Debug Info)
      shell: docker logs --tail 50 backend
      register: app_logs
      ignore_errors: yes

    - name: Print Logs to Jenkins Console
      debug:
        var: app_logs.stdout_lines

# 2. Frontend Deploy
- name: Deploy Frontend Application
  hosts: frontend
  become: yes
  tasks:
    - name: Stop old frontend container (if running)
      shell: docker stop frontend || true

    - name: Remove old frontend container
      shell: docker rm frontend || true

    - name: Pull Docker Image
      shell: docker pull chamod12/car-frontend:latest

    - name: Run Frontend Container
      shell: >
        docker run -d --name frontend -p 5173:5173
        -e VITE_API_URL="http://3.238.155.37:5000/api"
        chamod12/car-frontend:latest