---
- name: Install Jenkins (Foolproof Method)
  hosts: jenkins
  become: true
  tasks:
    # 1. පරණ ලෙඩ දෙන Jenkins repo files අයින් කරමු (apt update fail වෙන එක නවත්තන්න)
    - name: Clean up old Jenkins repo list files
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - /etc/apt/sources.list.d/jenkins*.list

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install prerequisite packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    # 2. Java දාමු
    - name: Install Java
      apt:
        name: openjdk-17-jre
        state: present

    - name: Download Jenkins signing key (required NO_PUBKEY 7198F4B714ABFC68)
      get_url:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x7198F4B714ABFC68
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: "0644"

    # 4. Repo එක එකතු කරමු
    - name: Add Jenkins Repo
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
        state: present
        filename: jenkins
        update_cache: no

    # 5. Cache   Update 
    - name: Update Apt Cache Manual
      apt:
        update_cache: yes

    # 6.  Jenkins  Install
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    # 7. Jenkins  Start
    - name: Start Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Ensure docker group exists
      group:
        name: docker
        state: present

    # 8. Docker  Jenkins 
    - name: Add Jenkins user to Docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    # 9. Restart Jenkins
    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted